apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: application1.mini.topic
  labels:
    strimzi.io/cluster: single-node-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    # This string designates the retention policy to use on old log segments. 
    # Valid values: delete | compact
    cleanup.policy: delete
    # This configuration controls the maximum time we will retain a log before we will 
    # discard old log segments to free up space if we are using the "delete" retention policy.
    # Value: 7 days (a week)
    # retention.ms: 604800000
    # Value: 1 days
    retention.ms: 86400000
    # This configuration controls the segment file size for the log. Retention and
    # cleaning is always done a file at a time so a larger segment size means fewer files
    # but less granular control over retention.
    # Value: 100MB
    segment.bytes: 104857600
